# Generated by Django 4.2.7 on 2024-02-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, upload_to='products/')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='goods.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ClothSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='products/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='ImageProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_p', to='goods.image')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, upload_to='products/')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='goods.brand', verbose_name='Бренд')),
                ('show_images', models.ManyToManyField(through='goods.ImageProductLink', to='goods.image')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип (категория)',
                'verbose_name_plural': 'Типы (категории)',
            },
        ),
        migrations.CreateModel(
            name='ProductSizeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='goods.size')),
            ],
            options={
                'verbose_name': 'Предложенные размеры',
                'verbose_name_plural': 'Предложенные размеры',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='goods.ProductSizeLink', to='goods.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='goods.type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='imageproductlink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_p', to='goods.product'),
        ),
        migrations.CreateModel(
            name='ImageClothLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_c', to='goods.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_c', to='goods.cloth')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='ClothSizeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='goods.cloth')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_sizes', to='goods.clothsize')),
            ],
            options={
                'verbose_name': 'Предложенные размеры',
                'verbose_name_plural': 'Предложенные размеры',
            },
        ),
        migrations.AddField(
            model_name='cloth',
            name='show_images',
            field=models.ManyToManyField(through='goods.ImageClothLink', to='goods.image'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='sizes',
            field=models.ManyToManyField(through='goods.ClothSizeLink', to='goods.clothsize'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='goods.type', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='banners/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.type', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.AddConstraint(
            model_name='productsizelink',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size'),
        ),
        migrations.AddConstraint(
            model_name='imageproductlink',
            constraint=models.UniqueConstraint(fields=('product', 'img'), name='unique_product_img'),
        ),
        migrations.AddConstraint(
            model_name='imageclothlink',
            constraint=models.UniqueConstraint(fields=('product', 'img'), name='unique_cloth_img'),
        ),
        migrations.AddConstraint(
            model_name='clothsizelink',
            constraint=models.UniqueConstraint(fields=('cloth', 'size'), name='unique_cloth_size'),
        ),
    ]
