# Generated by Django 4.2.7 on 2024-02-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
        migrations.AlterModelOptions(
            name='clothsize',
            options={'verbose_name': 'Размер одежды', 'verbose_name_plural': 'Размеры одежды'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Обувь', 'verbose_name_plural': 'Обувь'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер обуви', 'verbose_name_plural': 'Размеры обуви'},
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
