# Generated by Django 4.2.7 on 2024-02-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_cloth_options_alter_clothsize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='goods.type', verbose_name='Категория'),
        ),
    ]
