# Generated by Django 4.2.7 on 2024-03-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='most_liked',
            field=models.BooleanField(default=False),
        ),
    ]
