# Generated by Django 4.2.7 on 2024-03-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_product_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
