# Generated by Django 4.2.7 on 2024-03-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_cloth_images_alter_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.type', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
