# Generated by Django 4.2.7 on 2024-05-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_remove_brand_slug_brand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='model',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='goods.model', verbose_name='Модель'),
        ),
    ]
